### ISSUE TITLE
Multiple binary packages for same git archive urls are created

### ISSUE THREAD

**Issue by Lupus** [OCamlPro/opam-bin#26]
I noticed that packages that have git url as a source archive result in new binary packages created upon each build. Is that expected?

**Comment by lefessan** [comment]
Yes, unfortunately, `opam-bin` computes the checksum of a package from its sources, including all sub-directories, so probably the `.git/` too. Maybe `opam-bin` should disregard some directories (`.git/`, `_build`, etc.) when scanning the sources, but it's always a bit dangerous...

**Comment by lefessan** [comment]
For now, I am adding an env variable `OPAM_BIN_EXCLUDE` that you can set to `.git,_build` for example before running `opam`. The default is to scan everything, I will try to see what better default we could have.

 https://github.com/OCamlPro/opam-bin/pull/22/commits/1413b10812f1f474ac75f66c78c6d629463c501b

**Comment by Lupus** [comment]
Sounds good! Having this parameter in config would also be handy. I'll give it a try!

**Comment by Lupus** [comment]
Opam pin fails for the commit that you referenced with `Commit not found on repository` error, pin command was:
```
$ opam pin add opam-bin https://github.com/OCamlPro/opam-bin.git#1413b10
```

Github says "This commit does not belong to any branch on this repository" when opening the link in your comment.

**Comment by Lupus** [comment]
Hm, managed to pin this commit via archive url...
```
opam pin -y https://github.com/OCamlPro/opam-bin/archive/1413b10812f1f474ac75f66c78c6d629463c501b.zip
```

**Comment by lefessan** [comment]
Indeed, the commit was in the PR that was not yet merged. I just merged it a few seconds ago, it should be in `master` now.

**Comment by Lupus** [comment]
Yay! I confirm that it works! Setting `OPAM_BIN_EXCLUDE` to `.git,_build` I now have everything installed from binary packages and no spurious binary packages are created. Thanks @lefessan !

**Comment by lefessan** [comment]
Wonderful, I also added an `exclude_dirs` option in the config file, that defaults to [ `.git`, `.hg`, `_darcs` ]. It is in this PR:
https://github.com/OCamlPro/opam-bin/pull/28

**Comment by Lupus** [comment]
Confirmed, latest master does not create new binary packages without any additional configuration. Thanks!
