### ISSUE TITLE
Fresh release on opam

### ISSUE THREAD

**Issue by Lupus** [OCamlPro/opam-bin#48]
We have to use pins to get latest features, as 1.0.0 release is pretty old... Is it possible to cut a new one and release to opam?
1.0.0 does not include "Remove patches_url link to typerex.org", so opam version is just broken as of now.

**Comment by lefessan** [comment]
Check v1.1.0 on opam in this PR: https://github.com/ocaml/opam-repository/pull/19060

**Comment by Lupus** [comment]
Cool, thanks!
